version: '3.8'

services:
  # Development Database
  db:
    image: postgres:15
    container_name: tariff_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - tariff_dev_network

  # PgAdmin for development
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tariff_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - tariff_dev_network

volumes:
  postgres_dev_data:
    driver: local

networks:
  tariff_dev_network:
    driver: bridge
