server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO

app:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expirationMs: ${JWT_EXPIRATION_MS:86400000} # 1 day
gemini:
  api:
    key: ${GEMINI_API_KEY:}

# NewsData.io API Configuration
# Get your API key from: https://newsdata.io/register
# Place your API key below (replace YOUR_NEWSDATA_API_KEY with actual key)
newsdata:
  api:
    key: ${NEWSDATA_API_KEY:}
# Swagger UI path: http://localhost:8080/swagger-ui/index.html
