server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-csd-db.cpa8somwae85.ap-southeast-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: lordshiva15_SRI
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO

app:
  jwt:
    secret: ${JWT_SECRET:fvbMVJWfii+dPc5Ih2W6s9IC7C+fIdZgC2B/VVnEjBM=}
    expirationMs: ${JWT_EXPIRATION_MS:86400000} # 1 day
gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyCxgqgrYbMCQs9178XiPkabKLKkMGi9q-g}

# NewsData.io API Configuration
# Get your API key from: https://newsdata.io/register
# Place your API key below (replace YOUR_NEWSDATA_API_KEY with actual key)
newsdata:
  api:
    key: ${NEWSDATA_API_KEY:pub_7713507262314bd18c0fb64c8536c7bc}
# Swagger UI path: http://localhost:8080/swagger-ui/index.html
